---

- name: Criar novos usuários
  hosts: ubuntu
  become: yes
  vars_prompt:
    - name: username
      prompt: Qual o seu nome?
      private: false

    - name: password
      prompt: Qual a sua senha?
      private: true
      encrypt: "md5_crypt"
      confirm: yes

    - name: shell
      prompt: Qual o seu shell?
      private: false

  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'Usuário: {{ username}} | Senha: {{ password }} | Shell: {{ shell }}'

    - name: Criar usuário
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "User created by ansible"
        shell: "{{ shell }}"
        home: "/home/{{ username }}"
        password: "{{ password }}"

...
