---

- name: Deploy OpenJDK
  hosts: ubuntu
  become: yes

  tasks:
    - name: Download OpenJDK
      ansible.builtin.get_url:
        url: https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb
        dest: /tmp
        mode: 0777

    - name: Instalar OpenJDK
      ansible.builtin.apt:
        deb: /tmp/jdk-17_linux-x64_bin.deb

...
