---

- name: Variáveis Externas
  hosts: ubuntu
  become: yes
  vars_files: packages.yml

  tasks:
    - name: Atualizar o SO
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Instalar packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest

    - name: Enable Service MariaDB
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

...


