---

- name: Deploy Barbearia
  hosts: all
  become: yes

  tasks:
    - name: Atualizar SO
      ansible.builtin.apt: 
        name: "*"
        state: latest
        update_cache: yes

    - name: Instalar Apache2
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: Parar o NGINX
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: no

    - name: Habilitar serviço
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar o Projeto para /var/www/html
      ansible.builtin.copy:
        src: . 
        dest: /var/www/html
        owner: root
        group: root

...
